# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_auto_20171130_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sunrise_updated',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sunset_updated',
        ),
    ]
