# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_auto_20171130_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='commute_updated',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
