# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_userprofile_commute_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='loc_1_time',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='loc_2_time',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
