# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_auto_20171130_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_name', models.TextField(blank=True, default=None, null=True)),
                ('alarm_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('profile', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.UserProfile')),
            ],
        ),
    ]
