# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_alarms_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alarm_active',
            field=models.BooleanField(default=False),
        ),
    ]
