# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_userprofile_alarm_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_name', models.TextField(blank=True, default=None, null=True)),
                ('reminder_time', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reminder_create_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminders',
            name='profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.UserProfile'),
        ),
    ]
