# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_auto_20171202_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='math_request_active',
            field=models.BooleanField(default=False),
        ),
    ]
