# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0011_userprofile_math_request_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sleep_active',
            field=models.BooleanField(default=False),
        ),
    ]
