# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0013_userprofile_search_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alarm_creating_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='alarm_creating_time',
            field=models.BooleanField(default=False),
        ),
    ]
