# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0014_auto_20171203_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alarm_deleting_specific',
            field=models.BooleanField(default=False),
        ),
    ]
