# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0015_userprofile_alarm_deleting_specific'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='voice',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
