# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0017_auto_20171205_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_setting_name',
            field=models.BooleanField(default=False),
        ),
    ]
