# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0019_userprofile_ai_setting_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='apple_iphone_dev_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
