# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0023_userprofile_ai_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='crypto_search_request',
            field=models.BooleanField(default=False),
        ),
    ]
