# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0024_userprofile_crypto_search_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_number', models.TextField(blank=True, default=None, null=True)),
                ('email_id', models.TextField(blank=True, default=None, null=True)),
                ('profile', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.UserProfile')),
            ],
        ),
    ]
