# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0025_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='unread_email_request',
            field=models.BooleanField(default=False),
        ),
    ]
