# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0026_userprofile_unread_email_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='unread',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='all_email_request',
            field=models.BooleanField(default=False),
        ),
    ]
