# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0027_auto_20171208_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='uber_address_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uber_car_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uber_car_seat_request',
            field=models.BooleanField(default=False),
        ),
    ]
