# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0028_auto_20171209_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_setting_volume',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
