# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0029_userprofile_ai_setting_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarms',
            name='daily',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alarms',
            name='going_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alarms',
            name='weekly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='alarm_creating_mode',
            field=models.BooleanField(default=False),
        ),
    ]
