# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0030_auto_20171210_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reminder_time_create_active',
            field=models.BooleanField(default=False),
        ),
    ]
