# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 05:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0031_userprofile_reminder_time_create_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='reminder_create_active',
            new_name='reminder_creating_name',
        ),
    ]
