# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0032_auto_20171211_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timer_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timer_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
